// harness-guard: enforces the SDD workflow inside opencode. Generated by @jorgegb/harness-init.
//
// - Project code can only be edited while a feature is `in_progress` and its spec is approved
//   (specs/<name>/APPROVED matches the current spec), or the feature has `"sdd": false`.
//   Specs, progress notes, docs, Markdown and feature_list.json are always editable.
// - No agent may write an APPROVED file or run `harness-init approve`, by any tool.
// - When a session that edited code goes idle, ./init.sh runs. If it fails, a top-level
//   session is told to fix it (at most MAX_FIX_ATTEMPTS times); sub-agents get a toast.
//
// For work outside the workflow, start opencode with HARNESS_GUARD=off (ignored under strict rigor).
// Only one export: opencode loads every export of a plugin file as a plugin.

import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { isAbsolute, join, relative, sep } from "node:path";

// "disabled" under strict rigor: HARNESS_GUARD=off is then ignored.
const ESCAPE_HATCH = "{{GUARD_ESCAPE_HATCH}}";
const MAX_FIX_ATTEMPTS = 2;
const INIT_TIMEOUT_MS = 10 * 60 * 1000;
const OUTPUT_TAIL_LINES = 40;

const EDIT_TOOLS = new Set(["edit", "write", "multiedit", "apply_patch"]);
const NON_CODE_DIRS = ["specs/", "progress/", "docs/", "openspec/"];
const NON_CODE_FILES = new Set(["feature_list.json"]);
const APPROVAL_PATH = /^specs\/[^/]+\/APPROVED$/;
const APPROVE_COMMAND = /harness-init\s+approve\b/;
const WRITES_FILE = /(>|\btee\b|\bcp\b|\bmv\b|\btouch\b|\bsed\s+-i|\brm\b|\bln\b|\binstall\b|\bdd\b)/;
const SPEC_FILES = ["requirements.md", "design.md", "tasks.md"];

const APPROVAL_DENIED =
  "Only a human can approve a spec. Ask them to review specs/<feature>/ and run `npx @jorgegb/harness-init approve <feature>` in their terminal.";

// Must match specHash() in harness-init's src/approve.ts and init.sh.
function specHash(specDir) {
  const hash = createHash("sha256");
  for (const file of SPEC_FILES) {
    let text = readFileSync(join(specDir, file), "utf-8").replaceAll("\r\n", "\n");
    if (file === "tasks.md") text = text.replace(/^(\s*[-*]\s+)\[[xX]\]/gm, "$1[ ]");
    hash.update(`${file}\0${text}\0`);
  }
  return hash.digest("hex");
}

function approvedHash(specDir) {
  const path = join(specDir, "APPROVED");
  if (!existsSync(path)) return null;
  const line = readFileSync(path, "utf-8").split("\n").find((l) => l.startsWith("sha256:"));
  return line ? line.slice("sha256:".length).trim() : "";
}

/** Why code may not be edited right now, or null if it may. */
function codeEditBlocker(directory) {
  let features;
  try {
    features = JSON.parse(readFileSync(join(directory, "feature_list.json"), "utf-8")).features ?? [];
  } catch {
    return "feature_list.json is missing or invalid, so no feature is in_progress";
  }
  const active = features.find((f) => f.status === "in_progress");
  if (!active) return "no feature is in_progress. Write and get a spec approved first";
  if (!active.sdd) return null;

  const specDir = join(directory, "specs", active.name);
  if (SPEC_FILES.some((f) => !existsSync(join(specDir, f)))) {
    return `specs/${active.name}/ is incomplete`;
  }
  const approved = approvedHash(specDir);
  if (approved === null) {
    return `the spec for "${active.name}" is not approved. A human must run \`npx @jorgegb/harness-init approve ${active.name}\``;
  }
  if (approved !== specHash(specDir)) {
    return `the spec for "${active.name}" changed after approval. A human must review it and re-run \`npx @jorgegb/harness-init approve ${active.name}\``;
  }
  return null;
}

function editedPaths(tool, args) {
  if (tool === "apply_patch") {
    const text = String(args?.patchText ?? "");
    return [...text.matchAll(/^\*\*\* (?:Add File|Update File|Delete File|Move to): (.+)$/gm)].map((m) => m[1].trim());
  }
  return args?.filePath ? [String(args.filePath)] : [];
}

/** Project-relative POSIX path, or null if outside the project. */
function projectPath(directory, path) {
  const rel = isAbsolute(path) ? relative(directory, path) : path;
  if (rel.startsWith("..")) return null;
  return rel.split(sep).join("/").replace(/^\.\//, "");
}

function isCode(rel) {
  return !(NON_CODE_FILES.has(rel) || rel.endsWith(".md") || NON_CODE_DIRS.some((d) => rel.startsWith(d)));
}

function runInit(directory) {
  return new Promise((resolve) => {
    execFile("bash", ["./init.sh"], { cwd: directory, timeout: INIT_TIMEOUT_MS, maxBuffer: 10 * 1024 * 1024 }, (error, stdout, stderr) => {
      resolve({ ok: !error, output: `${stdout ?? ""}${stderr ?? ""}` });
    });
  });
}

export const HarnessGuard = async ({ client, directory }) => {
  const guardOff = () => ESCAPE_HATCH !== "disabled" && process.env.HARNESS_GUARD === "off";
  const touchedCode = new Set();
  const fixAttempts = new Map();

  const toast = (message, variant) =>
    client.tui.showToast({ body: { message, variant } }).catch(() => {});
  const log = (level, message) =>
    client.app.log({ body: { service: "harness-guard", level, message } }).catch(() => {});

  async function isTopLevel(sessionID) {
    try {
      const res = await client.session.get({ path: { id: sessionID } });
      return !res?.data?.parentID;
    } catch {
      return false;
    }
  }

  return {
    "tool.execute.before": async (input, output) => {
      if (guardOff()) return;

      if (input.tool === "bash") {
        const command = String(output.args?.command ?? "");
        if (APPROVE_COMMAND.test(command) || (/APPROVED/.test(command) && WRITES_FILE.test(command))) {
          throw new Error(APPROVAL_DENIED);
        }
        return;
      }

      if (!EDIT_TOOLS.has(input.tool)) return;
      for (const raw of editedPaths(input.tool, output.args)) {
        const rel = projectPath(directory, raw);
        if (rel === null) continue;
        if (APPROVAL_PATH.test(rel)) throw new Error(APPROVAL_DENIED);
        if (!isCode(rel)) continue;
        const blocker = codeEditBlocker(directory);
        if (blocker) throw new Error(`harness-guard blocked editing ${rel}: ${blocker}.`);
      }
    },

    "tool.execute.after": async (input) => {
      if (!EDIT_TOOLS.has(input.tool)) return;
      const paths = editedPaths(input.tool, input.args).map((p) => projectPath(directory, p));
      if (paths.some((rel) => rel !== null && isCode(rel))) touchedCode.add(input.sessionID);
    },

    event: async ({ event }) => {
      if (event.type !== "session.idle" || guardOff()) return;
      const sessionID = event.properties?.sessionID;
      if (!touchedCode.has(sessionID) || !existsSync(join(directory, "init.sh"))) return;
      touchedCode.delete(sessionID);

      const result = await runInit(directory);
      if (result.ok) {
        fixAttempts.delete(sessionID);
        await toast("init.sh passed", "success");
        return;
      }

      const attempts = (fixAttempts.get(sessionID) ?? 0) + 1;
      fixAttempts.set(sessionID, attempts);
      const tail = result.output.trimEnd().split("\n").slice(-OUTPUT_TAIL_LINES).join("\n");
      await log("warn", `init.sh failed (attempt ${attempts})`);

      if (attempts > MAX_FIX_ATTEMPTS) {
        await toast(`init.sh still failing after ${MAX_FIX_ATTEMPTS} fix attempts. A human needs to look.`, "error");
        return;
      }
      if (!(await isTopLevel(sessionID))) {
        await toast("init.sh failed after a sub-agent's changes. The reviewer must not approve.", "error");
        return;
      }
      await toast("init.sh failed. Asking the agent to fix it.", "error");
      await client.session
        .prompt({
          path: { id: sessionID },
          body: {
            parts: [
              {
                type: "text",
                text: `harness-guard: ./init.sh failed after your changes (attempt ${attempts}/${MAX_FIX_ATTEMPTS}). Fix it before you finish. Do not weaken or delete tests to make it pass.\n\n\`\`\`\n${tail}\n\`\`\``,
              },
            ],
          },
        })
        .catch((err) => log("error", `could not prompt session: ${err}`));
    },
  };
};
